### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by bakwc** [Roninsc2/arkanoid#5]
1) создать файлы image_storer.h & image_storer.cpp, в них создать класс TImageStorer который будет отвечать за загрузку, хранение и отрисовку требуемых картинок
2) сделать файлы field.h & field.cpp, в них создать классс TField, который будет отвечать за хранение игрового поля, загрузку его из файла, переход к следующему уровню и пересчёт состояния. В нём хранить блоки и биту.
2) создать файл drawer.h / drawer.cpp в котором сделать класс, занимающийся отрисовкой состояния игрового поля.
3) в widget.h / cpp использовать перечисленные выше файлы / классы.

**Comment by charnad** [comment]
Я предложу ImageLoader вместо Storer. Слова-то такого и нет по-моему.
Да и drawer это ящик комода. Можно например Renderer назвать. Ну это так, мелочи.

**Comment by bakwc** [comment]
ImageManager?

**Comment by charnad** [comment]
Да, менеджер тоже по-моему хорошее слово
